Fix bug when using SecurityRequirement
When using the SecurityRequirement in MetadataModule , it will get the errors:
```
Nancy.RequestExecutionException: Oh noes! ---< System.InvalidCastException: Unable to cast object of type 'Swagger.ObjectModel.SecuritySchemes' to type 'System.String'.
   at Swagger.ObjectModel.SwaggerModel.SwaggerSerializerStrategy.ToObject(IDictionary source)
   at Swagger.ObjectModel.SwaggerModel.SwaggerSerializerStrategy.TrySerializeUnknownTypes(Object input, Object& output)
   at Swagger.ObjectModel.SimpleJson.SerializeValue(IJsonSerializerStrategy jsonSerializerStrategy, Object value, StringBuilder builder)
   at Swagger.ObjectModel.SimpleJson.SerializeObject(IJsonSerializerStrategy jsonSerializerStrategy, IEnumerable keys, IEnumerable values, StringBuilder builder)
...
```
Because the method `ToObject`  specify a string value which cause the `SecuritySchemes`  cast unsuccessfully!